site_name: Iconclass

site_name: ICONCLASS
site_url: https://iconclass.org/
repo_url: https://github.com/shnonbru/Iconclass-documentation.git

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - navigation.top
    - header.autohide
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: about.md
  - Beginner's Guide : beginner-guide.md
  - Essential Concepts : essential-concepts.md
  - Examples : examples.md
  - Bibliography : bibliography.md
  - Contact : contact.md

